title: "Atomistic Simulation of C–S–H — Course Manual"
author: "Hegoi Manzano"
language: en

execute:
  execute_notebooks: "off"   # safe for CI

only_build_toc_files: true

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
    - deflist
    - linkify

sphinx:
  config:
    html_theme: furo
    html_title: "Atomistic Simulation of C–S–H"
    # Optional: syntax highlighting styles (Furo supports separate light/dark)
    pygments_style: "default"
    pygments_dark_style: "native"
    # Optional: logo & favicon later
    html_logo: images/logo.png
    html_last_updated_fmt: "%Y"
    html_show_copyright: true
    copyright: "© 2025 Hegoi Manzano — Made with Sphinx and Furo"
    # html_favicon: images/favicon.ico
    # Optional: custom CSS (see next section)
    # html_static_path: ["_static"]
    # html_css_files: ["custom.css"]

plugins:
  - jemoji

latex:
  latex_engine: xelatex
