title: Atomistic Simulation of C-S-H with PyCSH and LAMMPS
author: Hegoi Manzano
logo: ''
execute:
  execute_notebooks: auto
latex:
  latex_engine: xelatex
sphinx:
  config:
    html_show_copyright: false
    html_theme_options:
      navigation_depth: 3
