title: "Atomistic Simulation of C–S–H — Course Manual"
author: "Hegoi Manzano"
language: en

execute:
  execute_notebooks: "off"

only_build_toc_files: true

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
    - deflist
    - linkify

sphinx:
  config:
    html_theme: pydata_sphinx_theme
    html_title: "Atomistic Simulation of C–S–H"
    html_theme_options:
      navigation_depth: 4
      show_nav_level: 2
      show_prev_next: true
      collapse_navigation: false
      header_links_before_dropdown: 6
      navbar_end:
        - theme-switcher
        - navbar-icon-links
      icon_links:
        - name: GitHub
          url: https://github.com/<user>/<repo>
          icon: fa-brands fa-github
          type: fontawesome
    # Optional logo / favicon
    # html_logo: images/logo.png
    # html_favicon: images/favicon.ico
    # Optional custom CSS
    # html_static_path: ["_static"]
    # html_css_files: ["custom.css"]

latex:
  latex_engine: xelatex
