name: build-and-deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: python -m pip install --upgrade pip
      - run: pip install -r docs/requirements.txt
        # Si tu requirements.txt está en la raíz, usa: pip install -r requirements.txt

      # Compila el libro que está dentro de docs/
      - run: jupyter-book build docs

      # Publica la carpeta generada docs/_build/html a gh-pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
